config/routes.rb
Rails.application.routes.draw do
  resources :countries
      devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  resources :pieces
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pieces#index"
end

app/models/piece.rb
class Piece < ApplicationRecord
after_create :hellothere
after_update :hellothere
def hellothere
@myscore="


\\version \"2.24.3\"


\\header {
  title = \"#{self.name}\"
  composer = \"#{composer} #{artist}\"
}

global = {
  \\key #{key_signature.sub(" "," \\")}
  \\numericTimeSignature
  \\time #{time_signature}
  \\tempo 4=#{bpm}
}



violin = \\relative c'' {
  \\global
  % En avant la musique.
  a b c d e f 
  
}

\\score {
  \\new Staff \\with {
    instrumentName = \"Violon\"
    midiInstrument = \"violin\"
  } \\violin
  \\layout { }
  \\midi { }
}




"
@score="

<lilypond fragment staffsize=26>
  \\key #{key_signature.sub(" "," \\")}
  \\numericTimeSignature
  \\time #{time_signature}
  \\tempo 4=#{bpm}
  c'4 d' e' f' g'2 g'
</lilypond>
"

p @score

wow="./public/uploads/"
hi=self.name.parameterize
p wow+hi

File.write(wow+"hello"+hi+".ly", @myscore)

File.write(wow+"hey"+hi+".html", @score)

File.write(wow+"hi"+hi+"hi.ly", "<lilypond>"+@myscore+"</lilypond>")
###
@hi=`(cd #{wow} && lilypond-book hi#{hi}hi.ly -f html --output hi#{hi})`
####

@hey=`(cd #{wow} && lilypond-book hey#{hi}.html -f html --output #{hi})`

@hello=`(cd #{wow} && ly highlight hello#{hi}.ly > hello#{hi}.html)`
p "(cd #{wow} && ly highlight hello#{hi}.ly > hello#{hi}.html)"

end

end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  before_action :set_piece, only: %i[ show edit update destroy ]

  # GET /pieces or /pieces.json
  def index
    @pieces = Piece.all
  end

  # GET /pieces/1 or /pieces/1.json
  def show
  end

  # GET /pieces/new
  def new
    @piece = Piece.new(key_signature: "c major")
  end

  # GET /pieces/1/edit
  def edit
  end

  # POST /pieces or /pieces.json
  def create
    @piece = Piece.new(piece_params)

    respond_to do |format|
      if @piece.save
        format.html { redirect_to @piece, notice: "Piece was successfully created." }
        format.json { render :show, status: :created, location: @piece }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pieces/1 or /pieces/1.json
  def update
    respond_to do |format|
      if @piece.update(piece_params)
        format.html { redirect_to @piece, notice: "Piece was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @piece }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pieces/1 or /pieces/1.json
  def destroy
    @piece.destroy!

    respond_to do |format|
      format.html { redirect_to pieces_path, notice: "Piece was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_piece
      @piece = Piece.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def piece_params
      params.expect(piece: [ :name, :time_signature, :key_signature, :title, :artist, :composer, :bpm ])
    end
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/views/pieces/_form.html.erb
<%= form_with(model: piece) do |form| %>
  <% if piece.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(piece.errors.count, "error") %> prohibited this piece from being saved:</h2>

      <ul>
        <% piece.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :time_signature, "comme 4/4, 4/8, 6/8, 3/8 etc.", style: "display: block" %>
    <%= form.text_field :time_signature %>
  </div>

  <div>
    <%= form.label :key_signature, style: "display: block" %>
<%keys=piece.key_signature.split(" ")%>
<select value="<%=keys[0]%>" id="key1" onchange="piece_key_signature.value=key1.value+' '+key2.value">
<%["a","b","c","cis","des","d", "dis","ees","e","f"].each do |h|%>
<option <%=keys[0] == h ? "selected=\"selected\"" : ""%> value="<%=h%>"><%=h%>
</option>
<%end%>
</select>
<select value="<%=keys[1]%>" id="key2" onchange="piece_key_signature.value=key1.value+' '+key2.value">
<%["major","minor"].each do |h|%>
<option <%=keys[1] == h ? "selected=\"selected\"" : ""%> value="<%=h%>"><%=h%>
</option>
<%end%>
</select>
    <%= form.hidden_field :key_signature %>

  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :artist, style: "display: block" %>
    <%= form.text_field :artist %>
  </div>

  <div>
    <%= form.label :composer, style: "display: block" %>
    <%= form.text_field :composer %>
  </div>

  <div>
    <%= form.label :bpm, style: "display: block" %>
    <%= form.text_field :bpm %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pieces/_piece.html.erb
<div id="<%= dom_id piece %>">
  <p>
    <%= piece.name %>
  </p>
</div>

app/views/pieces/edit.html.erb
<% content_for :title, "Editing piece" %>

<h1>Editing piece</h1>

<%= render "form", piece: @piece %>

<br>

<div>
  <%= link_to "Show this piece", @piece %> |
  <%= link_to "Back to pieces", pieces_path %>
</div>

app/views/pieces/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Pieces" %>

<h1>Pieces</h1>

<div id="pieces">
  <% @pieces.each do |piece| %>
    <%= render piece %>
    <p>
      <%= link_to "Show this piece", piece %>
    </p>
  <% end %>
</div>

<%= link_to "New piece", new_piece_path %>

app/views/pieces/new.html.erb
<% content_for :title, "New piece" %>

<h1>New piece</h1>

<%= render "form", piece: @piece %>

<br>

<div>
  <%= link_to "Back to pieces", pieces_path %>
</div>

app/views/pieces/show.html.erb
<p style="color: green"><%= notice %></p>

<p><%= @piece.name %></p>
<h1> Add New passage to the piece</h1>


<iframe style="width:90%;height:200px;" src="/uploads/<%=@piece.name.parameterize%>/hey<%=@piece.name.parameterize%>.html">
</iframe>
<iframe style="width:90%;height:200px;" src="/uploads/hi<%=@piece.name.parameterize%>/hi<%=@piece.name.parameterize%>hi.html">
</iframe>
<iframe style="width:90%;height:200px;" src="/uploads/hello<%=@piece.name.parameterize%>.html">
</iframe>

<br>



<div>
  <%= link_to "Edit this piece", edit_piece_path(@piece) %> |
  <%= link_to "Back to pieces", pieces_path %>

  <%= button_to "Destroy this piece", @piece, method: :delete %>
</div>